baseURL = "https://albertlg.github.io/blog.albertlg.com/"
languageCode = "es-es"
title = "Yo soy Albert LG... y tu no."
DisqusShortname = "albertlg-blog"
theme = "ananke"
paginate = 5
pluralizelisttitles = false
canonifyurls = true
publishDir = "docs"
disableLanguages = [""]

[outputs]
    home = ["html", "json"]

[permalinks]
  post = "/:slug/"


