[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

# ==========
# REDIRECCIONES DE DOMINIOS
# ==========

[[redirects]]
  from = "https://albertlg.netlify.com/*"
  to = "https://albertlg.com/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://blog.albertlg.com/*"
  to = "https://albertlg.com/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/blog"
  to = "https://albertlg.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/blog/*"
  to = "https://albertlg.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect

# ==========
# REDIRECCIONES ESPECÍFICAS
# ==========

[[redirects]]
  from = "/ca/software-al-vino-351701/"
  to = "/ca/del-software-al-vi/"
  status = 301
  force = false
