[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

# ==========
# REDIRECCIONES DE DOMINIOS
# ==========

[[redirects]]
  from = "https://albertlg.netlify.com/*"
  to = "https://albertlg.com/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "https://blog.albertlg.com/*"
  to = "https://albertlg.com/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/blog"
  to = "https://albertlg.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect

[[redirects]]
  from = "/blog/*"
  to = "https://albertlg.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect

# ==========
# REDIRECCIONES ESPECÍFICAS
# ==========

[[redirects]]
  from = "/ca/tricefalia-reflexiones-esponja-1181188/"
  to = "/ca/tricefalia-reflexions-esponja/"
  status = 301
  force = false

[[redirects]]
  from = "/ca/software-al-vino-351701/"
  to = "/ca/del-software-al-vi/"
  status = 301
  force = false

#[[redirects]]
#  from = ""
#  to = ""
#  status = 301
#  force = false

[[redirects]]
  from = "/en/tricefalia-reflexiones-esponja-1181188/"
  to = "/en/tricefalia-reflections-sponge/"
  status = 301
  force = false

[[redirects]]
  from = "/en/software-al-vino-351701/"
  to = "/en/from-software-to-wine/"
  status = 301
  force = false

#[[redirects]]
#  from = ""
#  to = ""
#  status = 301
#  force = false
